# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f3ac1cedd0c947b08acb2dde75e030c700b8eb6b7b4251ae05fab3b90cb2f4702dcffb7aeffebfcaabb3cb7e36b0fcf7fbee8450d9d2363e6a2c7e4a06c8b1

test:
  secret_key_base: 7446702fa0b577d4cdf520e6c8b1b0666732a117b30ef13a9ad4c6a65485f47cf0d2e365413e62aa192f60082753b4dced8c84847acabca178e1295e0d1b6b32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
